check_code:
    path: '/{lang}'
    controller: 'App\Controller\Landing::checkCode'
    requirements:
        lang: 'de|'

upload_file:
    path: '/upload'
    controller: 'App\Controller\UploadFile::upload'
