landing:
    path: '/{lang}'
    controller: 'App\Controller\LandingController::checkCode'
    requirements:
        lang: 'de|'

upload_file:
    path: '/upload'
    controller: 'App\Controller\UploadFileController::upload'
    methods: [POST]

check_test:
    path: '/check/test'
    controller: 'App\Controller\CheckTestController::checkTest'

login:
    path: '/login'
    controller: 'App\Controller\LoginController::login'
    methods: [GET, POST]

system:
    path: '/system'
    controller: 'App\Controller\SystemController::showSystemData'
    methods: [GET]

logout:
    path: '/logout'
    controller: 'App\Controller\LogoutController::logout'

email:
    path: '/send/email'
    controller: 'App\Controller\EmailController::checkEmail'
    methods: [POST]


