landing:
    path: '/{lang}'
    controller: 'App\Controller\LandingController::checkCode'
    requirements:
        lang: 'de|'

upload_file:
    path: '/upload'
    controller: 'App\Controller\UploadFileController::upload'
    methods: [POST]

check_test:
    path: '/check/test'
    controller: 'App\Controller\CheckTestController::checkTest'

